### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by nader324** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#1]
hi bro
i have some problem to instal passwall
can you instruct me?

**Comment by amirhosseinchoghaei** [comment]
Drood bar shoma id telegrametoon ro befrestid

**Comment by amirhosseinchoghaei** [comment]
> Collected errors:
> 
> * opkg_download: Failed to download https://free.nchc.org.tw/osdn/storage/g/o/op/openwrt-passwall-build/releases/packages-22.03/mipsel_24kc/passwall2/Packages.gz, wget returned 4.
> * opkg_download: Check your network settings and connectivity.


Drood bar shoma id telegrametoon ro befrestid

**Comment by nader324** [comment]
salam dadash
nader324

**Comment by nader324** [comment]
Thanks for your help and kindness

**Comment by aetrekov** [comment]
> Thanks for your help and kindness

Have you solved the problem? If yes, then tell me how. Thank you in advance!
