### ISSUE TITLE
آپدیت openwrt

### ISSUE THREAD

**Issue by Shirinebra** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#10]
سلام
میخواستم بپرسم میشه نسخه سازگار با 23.05.0 منتشر کنید؟

**Comment by amirhosseinchoghaei** [comment]
درود ، درحال حاضر Passwall2 سازگار هستش ، میتونید فعلا از این نسخه استفاده بفرمایید تا آپدیت جدید منتشر بشه ...
