### ISSUE TITLE
Stablish internet connection after Passwall connection

### ISSUE THREAD

**Issue by miladnorouziii** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#11]
salam. aya emkanesh hast k beshe router ro juri tanzim kard k tanha vaghti ba movafaghiat vasl shod b server etesal internet o bargharar kone? yani dasgah aslan ip iran nagire. ba script neveshtan ee chizi mishe kari vasash kard?

**Comment by amirhosseinchoghaei** [comment]
درود ، همین الان هم همینطور هستش شما کانفیگ رو از سمت سرور قطع کنید اینترنت شما هم قطع خواهد شد ، تا زمانی که کانفیگ را مجدد فعال کنید .... تا زمانی که پسوال روشن باشد قابلیت کیل سوییچ هم دیفالت فعال میباشد ...
