### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by rbsdotnet** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#12]
سلام دوست عزیز
سپاس از شما
کار من راه افتاد من Xiami 4A Gigabit  داشتم و بعد از انجام روش شما کاملا تونستم V2ray رو راه اندازی کنم
خواستم تشکر کنم از شما ، پاینده باشید
❤️❤️❤️❤️❤️

**Comment by amirhosseinchoghaei** [comment]
درود بر شما

لطف دارید ممنونم بابت انرژی خوبتون ...
