### ISSUE TITLE
امکان اضافه کردن سابسکریپشن

### ISSUE THREAD

**Issue by rbsdotnet** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#13]
سلام دوست عزیز
آیا امکان اضافه کردن لینک Subscription وجود داره ؟ اگر بله در کدام قسمت هست

**Comment by amirhosseinchoghaei** [comment]
درود ، در تب node subscription در انتهای صفحه دکمه Add را بزنید و اضافه کنید

**Comment by rbsdotnet** [comment]
الان اضافه کردم در کدام قسمت باید دریافت رو بزنم؟

**Comment by rbsdotnet** [comment]
سپاس درست شد
باز هم تشکر میکنم واقعا کارت عالی بود 
❤️❤️😊😊😊❤️❤️❤️👌👌👌👌
