### ISSUE TITLE
خطای Passwall

### ISSUE THREAD

**Issue by rbsdotnet** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#14]
من روتر رو ریست فکتوری کردم بعد خواستم دوباره نصب کنم این خطا رو بهم میده

Downloading 'https://raw.githubusercontent.com/amirhosseinchoghaei/mi4agigabit/main/amirhossein.sh'
Connecting to 185.199.110.133:443
Writing to 'amirhossein.sh'
amirhossein.sh       100% |*******************************|  5194   0:00:00 ETA
Download completed (5194 bytes)
Running as root...
Version: 22.03.5
 Maybe You get Some Errors on 22.03.5 ! Try 22.03.4 or less ...

Architecture: mipsel_24kc
 Architecture : OK
ls: /etc/init.d/passwall: No such file or directory
 OOPS ! First Install Passwall on your Openwrt .

**Comment by amirhosseinchoghaei** [comment]
rm -f passwallx.sh && wget https://raw.githubusercontent.com/amirhosseinchoghaei/Passwall/main/passwallx.sh && chmod 777 passwallx.sh && sh passwallx.sh

**Comment by rbsdotnet** [comment]
کدها چندجا بود یه لحظه اشتباه کردم
