### ISSUE TITLE
بازنشدن یوتیوب و فیسبوک

### ISSUE THREAD

**Issue by OneLegChicken** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#16]
درود. یک هفته پیش بنده کانفیگ vless در سرور خارج ساختم و اونو توی passwall اضافه کردم و تا امروز کار میکرد ولی از امروز  یوتیوب و فیسبوک باز نمیشن همون کانفیگ رو وقتی توی گوشی و ویندوز ران میکنم هر دو سایت یوتیوب و فیسبوک بالا میاد ولی وقتی توی پنل passwall وارد میکنم یوتیوب و فیسبوک و یه سری سایت دیگه بالا نمیاد با اینکه تلگرام و اینستاگرام و واتساپ و ... کارمیکنن. سرور خارج رو از 3 دیتاسنتر مختلف امتحان کردم ولی مشکل حل نشد. 
در کانفیگ های vless که در اونها از تانل استفاده شده مشکلی ندارن و کار میکنه. 
تنظیمات خاصی درمورد DNS یا Firewall باید انجام بدم؟

>   ISP : MobinNet
>   router : Xiaomi Mi Router 4A Gigabit Edition
>   openwrt version : 22.03.5 
>   passwall version :  4.71-2-smartdns-dev
>   x-ray version : 1.8.6

**Comment by amirhosseinchoghaei** [comment]
درود ، اگر تلگرامتون باز میشه پس مشکل شما دی ان اس هستش ، لطفا از منوی پسوال تب DNS گزینه XRAY را انتخاب کنید ... سپس fake DNS را فعال کنید ...  سپس روی حالت Remote DNS قرار بدید و سیو کنید و بعد گزینه Clear IPSET را بزنید تا تنظیمات اعمال شود ...
