### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by Javi3y** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#19]
خسته نباشید میشه این رو روی x86 نصب کرد؟
چه مشکلی داره که قبول نمیکنه روی x86 نصب بشه
میخواستم تو یه lxc تو پراکسماکس بزنم

**Comment by amirhosseinchoghaei** [comment]
درود ، به راحتی نصب میشه و مشکلی نداره ... میتونید از نسخه آماده ای که براتون قرار دادم داخل vmware استفاده کنید :

https://www.mediafire.com/file/krekh9cfubekf7m/KIMTCHI.ova/file
