### ISSUE TITLE
Didnt work on mips_24kc Architecture

### ISSUE THREAD

**Issue by Sepehrdibaj** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#21]
Hi dear Amirhossein, i try to instal on mi router A4 gigabit but didnt completely instal , 
Oops : Your Architecture is Not compatible

**Comment by amirhosseinchoghaei** [comment]
سلام مدل روتر اگر 4A Gigabit باشه امکان نداره نصب نشه براتون ... مگر نسخه اینترنشنال نباشه !

**Comment by Sepehrdibaj** [comment]
اطمینان دارم که گلوبال هست ، با one step اقدام به نصب کردم ، ایا راه جایگزینی هست ؟ ممنون میشم روش برای حل مشکل معرفی کنید

**Comment by amirhosseinchoghaei** [comment]
نسخه openwrt را اعلام کنید

**Comment by Sepehrdibaj** [comment]
22.03.3

**Comment by amirhosseinchoghaei** [comment]
تلگرام پیام بدید امکان نداره !

**Comment by Sepehrdibaj** [comment]
مشکل حل شد دوباره زدم اما خیلی کند و ضعیف عمل می کنه علتش چی هست ؟ دقیقا با همون سرور هایی که روی ویندوز و ios خوب جواب میده تست کردم

**Comment by amirhosseinchoghaei** [comment]
احتمالا کانفیگ سنگین tls دار ران کردید ، در ضمن روتر شیائومی 4a gig به شدت ضعیفه و نمیشه روش حساب کرد 

مدل پیشنهادی : Xiaomi AX3000T

**Comment by Sepehrdibaj** [comment]
من قبلا سرور های شادو رو با Shadowsocks Libev وصل می کردم خیلی خوب کار می کرد اما دیدم حذف شده ، چه طوری میشه جدا نصبش کرد ؟

**Comment by Sepehrdibaj** [comment]
مهندس یه سوال url test با چند سرور زدن timeout میده ولی سرور ها کار می کنه باید کاری انجام بشه روش تا جواب درست بده ؟

**Comment by amirhosseinchoghaei** [comment]
سلام ، زیر مجموعه چه هسته ای هستید ؟ سینگ باکس ؟

**Comment by Sepehrdibaj** [comment]
نه از Shadowsocks Libev استفاده می کنم رو ورژن هایی قبلی passwall جواب میدان availablety تست بود اما رو ورژن جدید url شده فقط timeout میده ،

**Comment by amirhosseinchoghaei** [comment]
از شادوساکس ایکس ری استفاده بفرمایید
