### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by miladnorouziii** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#23]
سلام و درود. خواستم ببینم با توجه به اینکه الان فرگمنت خیلی خوب جواب میده آیا امکانش هست که آپدیت جدیدی ارائه به روی 4a gigabit بتونیم ازش استفاده کنیم؟

**Comment by amirhosseinchoghaei** [comment]
سلام آپدیت کنید این قابلیت در دسترس میباشد
