### ISSUE TITLE
فیلتر شدن ادرس دانلود ایکس ری در ایران*سل

### ISSUE THREAD

**Issue by Graveyard9988** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#5]
درود
در صورت امکان لینک فایل xray را تغییر دهید چرا که روی ایران*سل فیلتر شده است

تشکر

**Comment by amirhosseinchoghaei** [comment]
درود بر شما ... در انتهای صفحه براتون آپدیت گذاشتم ، دستور Update رو اجرا کنید لطفا .

**Comment by Graveyard9988** [comment]
سپاس
عینا همون دستور را در cmd بی کم و کاست وارد کنم درسته؟
