### ISSUE TITLE
Install custom firmware on 4A gigabit

### ISSUE THREAD

**Issue by xxamr** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#7]
Hi
How can install openwrt on mi 4a gigabit?
I bought two 4a router but it’s not possible to install custom firmware on it

**Comment by amirhosseinchoghaei** [comment]
Hi there , just install ubuntu on vmware workstation and follow these steps : 
https://www.youtube.com/watch?v=VxzEvdDWU_s&t=45s&ab_channel=HoddysGuides

**Comment by xxamr** [comment]
Can I do the procedure in OSX terminal?

**Comment by amirhosseinchoghaei** [comment]
Maybe it works !
