### ISSUE TITLE
sing-box core on openwrt luci passwall

### ISSUE THREAD

**Issue by Wasoud** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#8]
Hi.
how can install and use sing-box core? for use tuic, hysteria, hysteria2, etc.
seems it need golang 1.20 and higher and openwrt 22.03.5 an less is not supported. 
is openwrt version 23.05 support that?

this package:
https://github.com/openwrt/packages/tree/openwrt-23.05/lang/golang

please release one line code of install passwall+singbox core same that for xray-core.
thanks.

**Comment by Wasoud** [comment]
this repo:
https://github.com/openwrt/packages/tree/openwrt-23.05/lang/golang

**Comment by amirhosseinchoghaei** [comment]
Hi there
What is your router model ?

**Comment by Wasoud** [comment]
ASUS RT-AX53U.

**Comment by amirhosseinchoghaei** [comment]
1- Download 23.05.0 firmware and upgrade
2- Plug in USB Disk to the router
3- SSH remote Command : wget https://raw.githubusercontent.com/amirhosseinchoghaei/Increase-openwrt-disk-space/main/exroot.sh && chmod 777 exroot.sh && sh exroot.sh

4- rm -f passwallx.sh && wget https://raw.githubusercontent.com/amirhosseinchoghaei/Passwall/main/passwallx.sh && chmod 777 passwallx.sh && sh passwallx.sh

done
