### ISSUE TITLE
Xiaomi Mi Router 4C

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt#9]
سلام مهندس جان خسته نباشید من نصب رو انجام دادم همه چیز عالی کار میکنه فقط ساب لینک عمل نمیکنه و اینکه رو مدل 4c میتونم نصب کنم یا نه سپاس از زحمت شما

**Comment by amirhosseinchoghaei** [comment]
درود ، روی مدل 4c نمیشه نصب انجام داد سخت افزار خیلی پایینی داره ، روی بعضی از ساب لینک ها حساس هستش و ممکنه کار نکنه ، به صورت دستی کانفیگ را اد کنید …
